In [1]:
print("Yoo wasssup!")

Yoo wasssup!


In [2]:
!nvidia-smi

Sat Nov 15 00:14:34 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 555.99                 Driver Version: 555.99         CUDA Version: 12.5     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce GTX 1650      WDDM  |   00000000:01:00.0 Off |                  N/A |
| N/A   56C    P8              6W /   50W |     248MiB /   4096MiB |     35%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [3]:
import torch 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)
print(torch.cuda.is_available())

2.5.1+cu121
True


### Tensors

In [4]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

Get tensor value


In [6]:
scalar.item()

7

In [7]:
vector = torch.tensor([1,2,3])

In [8]:
vector

tensor([1, 2, 3])

In [9]:
vector.ndim

1

In [10]:
vector.shape
vector[1]

tensor(2)

In [11]:
matrix = torch.tensor([[1,2], [3,4]])
matrix

tensor([[1, 2],
        [3, 4]])

In [12]:
matrix.ndim

2

In [13]:
matrix.shape

torch.Size([2, 2])

In [14]:
matrix[1][0]

tensor(3)

In [15]:
tensor = torch.tensor([[[1,2,1],[3,4,2]],
                       [[4,5,3], [7,8,4]]])
tensor

tensor([[[1, 2, 1],
         [3, 4, 2]],

        [[4, 5, 3],
         [7, 8, 4]]])

In [16]:
tensor.shape

torch.Size([2, 2, 3])

In [17]:
tensor.ndim

3

### Random Tensors

They are very important, cause neural networks start with tensor full of rand num and adjust that number


In [18]:
rand_tensor = torch.rand(3,3,4)
rand_tensor

tensor([[[0.4716, 0.9873, 0.8888, 0.8759],
         [0.1371, 0.5285, 0.2122, 0.6880],
         [0.8275, 0.1198, 0.0179, 0.7309]],

        [[0.8275, 0.9137, 0.8893, 0.5415],
         [0.7297, 0.1928, 0.9704, 0.0960],
         [0.3138, 0.6955, 0.4692, 0.0411]],

        [[0.1033, 0.3001, 0.6235, 0.0302],
         [0.8135, 0.9799, 0.3607, 0.1983],
         [0.4064, 0.0990, 0.6553, 0.4868]]])

In [19]:
rand_tensor.ndim


3

In [20]:
rand_img = torch.rand(224,224,3) #images are used like this
rand_img.shape, rand_img.ndim

(torch.Size([224, 224, 3]), 3)

In [21]:
rand_tens = torch.rand(3,4)
rand_tens

tensor([[0.2997, 0.9825, 0.8659, 0.9918],
        [0.6785, 0.7315, 0.9473, 0.6090],
        [0.8754, 0.1103, 0.9287, 0.8575]])

### Zeros and ones

In [22]:
zero = torch.zeros(3,4)
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
zero * rand_tens

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [24]:
one = torch.ones(size= (3,4), dtype=torch.int32)
one

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=torch.int32)

### range and tensors-like

In [25]:
one_range = torch.arange(1,100, 7) ## start, end, step
one_range

tensor([ 1,  8, 15, 22, 29, 36, 43, 50, 57, 64, 71, 78, 85, 92, 99])

In [26]:
ten_zero = torch.zeros_like(one_range)
ten_zero

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [27]:
ten_ones = torch.ones_like(one_range)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

### tensor datatypes

In [28]:
f32 = torch.tensor([3.,6.,9.],
                   dtype=None, #datatype
                   device="cuda", #device: cpu or cuda
                   requires_grad=False #smthing related to tracking gradients ig
                   )
f32

tensor([3., 6., 9.], device='cuda:0')

In [29]:
f16 = f32.type(torch.half) # can be written as flaot16 and half both
f16

tensor([3., 6., 9.], device='cuda:0', dtype=torch.float16)

In [30]:
f16 * f32

tensor([ 9., 36., 81.], device='cuda:0')

In [31]:
some_tens = torch.rand(size=(2,3), device="cuda", dtype=torch.float16)
some_tens

tensor([[0.5654, 0.1780, 0.5723],
        [0.8306, 0.1656, 0.2878]], device='cuda:0', dtype=torch.float16)

In [32]:
some_tens.dtype, some_tens.shape, some_tens.device

(torch.float16, torch.Size([2, 3]), device(type='cuda', index=0))

### Manupulating Tensors


In [33]:
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [34]:
tensor * 10

tensor([10, 20, 30])

In [35]:
tensor / 10

tensor([0.1000, 0.2000, 0.3000])

In [36]:
tensor - 1

tensor([0, 1, 2])

In [37]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [38]:
torch.add(tensor,2)

tensor([3, 4, 5])

In [39]:
torch.sub(tensor,10)

tensor([-9, -8, -7])

In [40]:
#matrix mul
torch.matmul(tensor, tensor)

tensor(14)

In [41]:
torch.matmul(torch.rand(2,3), torch.rand(3,4))

tensor([[0.5725, 0.4644, 0.9929, 1.0301],
        [0.6389, 0.5086, 0.7303, 0.8333]])

In [42]:
torch.matmul(torch.rand(2,3), torch.rand(4,3).T)

tensor([[1.7688, 0.8682, 1.1756, 1.2366],
        [1.0317, 0.5188, 0.8439, 0.7463]])

In [43]:
torch.mm(torch.rand(2,3), torch.rand(3,2)) #mm is same as matmul

tensor([[0.6888, 0.9102],
        [0.8590, 1.3715]])

### Tensor Aggregation

In [44]:
x = torch.arange(2,50,7, dtype=torch.float32)
x

tensor([ 2.,  9., 16., 23., 30., 37., 44.])

In [45]:
torch.min(x), x.min()

(tensor(2.), tensor(2.))

In [46]:
torch.max(x), x.max()

(tensor(44.), tensor(44.))

In [47]:
torch.mean(x), x.mean()

(tensor(23.), tensor(23.))

In [48]:
torch.mean(x.type(torch.float)) # can be useful if you dont't want to change the datatype of the og tensor


tensor(23.)

In [49]:
torch.sum(x), x.sum()

(tensor(161.), tensor(161.))

### Positional min and max

In [50]:
x.argmin() # returns the index value of min value

tensor(0)

In [51]:
x[0]

tensor(2.)

In [52]:
x.argmax() # returns index value of the max value

tensor(6)

In [53]:
x[6]

tensor(44.)

### Reshaping, stacking, squeezing, unsqueezing

In [54]:
a = torch.arange(0,4).reshape(2,2)
b = torch.arange(4,8).reshape(2,2)


In [55]:
a.reshape(4)

tensor([0, 1, 2, 3])

In [56]:
a.reshape(4,1)

tensor([[0],
        [1],
        [2],
        [3]])

In [57]:
a.reshape(1,4)

tensor([[0, 1, 2, 3]])

In [58]:
#viewwwwwwwwww
t = a.view(4)  #a is actually of (2,2) shape
t               #t shares the same memory a does

tensor([0, 1, 2, 3])

In [59]:
t[0] = 1 #since they share the same memory making the changes to t will reflect on a aswell
t,a

(tensor([1, 1, 2, 3]),
 tensor([[1, 1],
         [2, 3]]))

In [60]:
#stackingggggggg
a_stacked = torch.stack([a,b])
a_stacked

tensor([[[1, 1],
         [2, 3]],

        [[4, 5],
         [6, 7]]])

In [61]:
a_stacked = torch.stack([a,b], dim=1)
a_stacked

tensor([[[1, 1],
         [4, 5]],

        [[2, 3],
         [6, 7]]])

In [62]:
a,b

(tensor([[1, 1],
         [2, 3]]),
 tensor([[4, 5],
         [6, 7]]))

In [63]:
a_stacked = torch.stack([a,b], dim=2)
a_stacked

tensor([[[1, 4],
         [1, 5]],

        [[2, 6],
         [3, 7]]])

In [64]:
a_stacked[0], a[0], b[0]

(tensor([[1, 4],
         [1, 5]]),
 tensor([1, 1]),
 tensor([4, 5]))

### Squeezeeeeeee
removes all single dims from target tensor

In [65]:
a_reshaped = a.reshape(1,1,4)

In [66]:
a_reshaped, a_reshaped.shape

(tensor([[[1, 1, 2, 3]]]), torch.Size([1, 1, 4]))

In [67]:
a_squeezed = a_reshaped.squeeze()
a_squeezed

tensor([1, 1, 2, 3])

### Unsuqeeze
adds a single dimension to a target tensor at a specific dim

In [68]:
a_unsqueezed = a_squeezed.unsqueeze(dim = 0)
a_unsqueezed, a_unsqueezed.shape


(tensor([[1, 1, 2, 3]]), torch.Size([1, 4]))

In [69]:
a_unsqueezed  = a_squeezed.unsqueeze(dim = 1)
a_unsqueezed, a_unsqueezed.shape

(tensor([[1],
         [1],
         [2],
         [3]]),
 torch.Size([4, 1]))

### Permute
rearrangment of dims, returns view of tensor

In [70]:
x_og = torch.rand(size=(224,224,3)) # color channel
x_og.shape

torch.Size([224, 224, 3])

In [71]:
x_permuted = x_og.permute(2,0,1) # rearrange by giving which dimenison to put where
x_permuted.shape                   # now it's rearranged to iykyk

torch.Size([3, 224, 224])

In [72]:
x_og[0,0,0] = 1

In [73]:
x_og[0,0,0], x_permuted[0,0,0] # seeee, it is a view of the original tensor

(tensor(1.), tensor(1.))

### Pytorch and NumPy

In [74]:
# to convert numpy to tensor -> torch.from_numpy(ndarray)

# pytorch tensor - > numpy array -> torch.Tensor.numpy()

In [ ]:
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) 
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

## GPUUUUUU

In [78]:
! nvidia-smi

Sat Nov 15 02:45:52 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 555.99                 Driver Version: 555.99         CUDA Version: 12.5     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce GTX 1650      WDDM  |   00000000:01:00.0 Off |                  N/A |
| N/A   46C    P8              5W /   50W |     163MiB /   4096MiB |     16%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [81]:
torch.cuda.is_available()

True

In [82]:
# device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [83]:
#Count GPUs
torch.cuda.device_count()

1

In [88]:
# On CPU
tensor = torch.tensor([1,2,3])
tensor, tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [89]:
#Using tensors on GPUUU, moving tensor to GPUU
tensor_gpu = tensor.to(device)
tensor_gpu, tensor_gpu.device


(tensor([1, 2, 3], device='cuda:0'), device(type='cuda', index=0))

In [90]:
# if tensor is on gpu, cant be transformed to numpy

tensor_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [93]:
#To fix that, we can set it to the cpu
tensor_back_on_cpu = tensor_gpu.cpu().numpy()
tensor_back_on_cpu #Sheeeeeeeeeeeesh

array([1, 2, 3])

In [94]:
tensor_gpu

tensor([1, 2, 3], device='cuda:0')