In [1]:
print("Yoo wasssup!")

Yoo wasssup!


In [2]:
!nvidia-smi

Mon Nov 10 23:42:22 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 555.99                 Driver Version: 555.99         CUDA Version: 12.5     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce GTX 1650      WDDM  |   00000000:01:00.0 Off |                  N/A |
| N/A   48C    P8              5W /   50W |     274MiB /   4096MiB |     18%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [3]:
import torch 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)
print(torch.cuda.is_available())

2.5.1+cu121
True


### Tensors

In [4]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

Get tensor value


In [6]:
scalar.item()

7

In [7]:
vector = torch.tensor([1,2,3])

In [8]:
vector

tensor([1, 2, 3])

In [9]:
vector.ndim

1

In [10]:
vector.shape
vector[1]

tensor(2)

In [11]:
matrix = torch.tensor([[1,2], [3,4]])
matrix

tensor([[1, 2],
        [3, 4]])

In [12]:
matrix.ndim

2

In [13]:
matrix.shape

torch.Size([2, 2])

In [14]:
matrix[1][0]

tensor(3)

In [15]:
tensor = torch.tensor([[[1,2,1],[3,4,2]],
                       [[4,5,3], [7,8,4]]])
tensor

tensor([[[1, 2, 1],
         [3, 4, 2]],

        [[4, 5, 3],
         [7, 8, 4]]])

In [16]:
tensor.shape

torch.Size([2, 2, 3])

In [17]:
tensor.ndim

3

### Random Tensors

They are very important, cause neural networks start with tensor full of rand num and adjust that number


In [18]:
rand_tensor = torch.rand(3,3,4)
rand_tensor

tensor([[[0.2050, 0.1859, 0.9162, 0.9230],
         [0.8891, 0.8323, 0.1573, 0.5903],
         [0.5325, 0.0923, 0.6564, 0.6085]],

        [[0.2396, 0.3354, 0.3853, 0.3776],
         [0.9050, 0.6767, 0.9360, 0.5371],
         [0.9733, 0.8300, 0.9588, 0.7060]],

        [[0.2672, 0.4753, 0.0891, 0.0906],
         [0.1598, 0.7964, 0.1429, 0.5017],
         [0.3638, 0.7250, 0.0029, 0.0246]]])

In [19]:
rand_tensor.ndim


3

In [20]:
rand_img = torch.rand(224,224,3) #images are used like this
rand_img.shape, rand_img.ndim

(torch.Size([224, 224, 3]), 3)

In [21]:
rand_tens = torch.rand(3,4)
rand_tens

tensor([[0.5908, 0.6981, 0.0147, 0.3138],
        [0.4079, 0.2803, 0.0449, 0.2043],
        [0.1385, 0.3869, 0.3087, 0.0964]])

### Zeros and ones

In [22]:
zero = torch.zeros(3,4)
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
zero * rand_tens

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [24]:
one = torch.ones(size= (3,4), dtype=torch.int32)
one

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=torch.int32)

### range and tensors-like

In [25]:
one_range = torch.arange(1,100, 7) ## start, end, step
one_range

tensor([ 1,  8, 15, 22, 29, 36, 43, 50, 57, 64, 71, 78, 85, 92, 99])

In [26]:
ten_zero = torch.zeros_like(one_range)
ten_zero

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [27]:
ten_ones = torch.ones_like(one_range)
ten_ones

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

### tensor datatypes

In [28]:
f32 = torch.tensor([3.,6.,9.],
                   dtype=None, #datatype
                   device="cuda", #device: cpu or cuda
                   requires_grad=False #smthing related to tracking gradients ig
                   )
f32

tensor([3., 6., 9.], device='cuda:0')

In [29]:
f16 = f32.type(torch.half) # can be written as flaot16 and half both
f16

tensor([3., 6., 9.], device='cuda:0', dtype=torch.float16)

In [30]:
f16 * f32

tensor([ 9., 36., 81.], device='cuda:0')

In [31]:
some_tens = torch.rand(size=(2,3), device="cuda", dtype=torch.float16)
some_tens

tensor([[0.6108, 0.6582, 0.2466],
        [0.6577, 0.7046, 0.3833]], device='cuda:0', dtype=torch.float16)

In [32]:
some_tens.dtype, some_tens.shape, some_tens.device

(torch.float16, torch.Size([2, 3]), device(type='cuda', index=0))

### Manupulating Tensors


In [33]:
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [34]:
tensor * 10

tensor([10, 20, 30])

In [35]:
tensor / 10

tensor([0.1000, 0.2000, 0.3000])

In [36]:
tensor - 1

tensor([0, 1, 2])

In [37]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [38]:
torch.add(tensor,2)

tensor([3, 4, 5])

In [39]:
torch.sub(tensor,10)

tensor([-9, -8, -7])

In [40]:
#matrix mul
torch.matmul(tensor, tensor)

tensor(14)

In [41]:
torch.matmul(torch.rand(2,3), torch.rand(3,4))

tensor([[0.6914, 0.4439, 0.4326, 1.0217],
        [1.0540, 0.4406, 0.5110, 1.1840]])

In [42]:
torch.matmul(torch.rand(2,3), torch.rand(4,3).T)

tensor([[0.2333, 0.8250, 0.2853, 0.4600],
        [0.1289, 0.0537, 0.0413, 0.2275]])

In [43]:
torch.mm(torch.rand(2,3), torch.rand(3,2)) #mm is same as matmul

tensor([[1.5502, 1.4682],
        [0.5567, 0.4710]])

### Tensor Aggregation

In [44]:
x = torch.arange(2,50,7, dtype=torch.float32)
x

tensor([ 2.,  9., 16., 23., 30., 37., 44.])

In [45]:
torch.min(x), x.min()

(tensor(2.), tensor(2.))

In [46]:
torch.max(x), x.max()

(tensor(44.), tensor(44.))

In [47]:
torch.mean(x), x.mean()

(tensor(23.), tensor(23.))

In [48]:
torch.mean(x.type(torch.float)) # can be useful if you dont't want to change the datatype of the og tensor


tensor(23.)

In [49]:
torch.sum(x), x.sum()

(tensor(161.), tensor(161.))

### Positional min and max

In [50]:
x.argmin() # returns the index value of min value

tensor(0)

In [51]:
x[0]

tensor(2.)

In [52]:
x.argmax() # returns index value of the max value

tensor(6)

In [53]:
x[6]

tensor(44.)

### Reshaping, stacking, squeezing, unsqueezing

In [61]:
a = torch.arange(0,4).reshape(2,2)
b = torch.arange(4,8).reshape(2,2)


In [62]:
a.reshape(4)

tensor([0, 1, 2, 3])

In [63]:
a.reshape(4,1)

tensor([[0],
        [1],
        [2],
        [3]])

In [64]:
a.reshape(1,4)

tensor([[0, 1, 2, 3]])

In [65]:
#viewwwwwwwwww
t = a.view(4)  #a is actually of (2,2) shape
t               #t shares the same memory a does

tensor([0, 1, 2, 3])

In [66]:
t[0] = 1 #since they share the same memory making the changes to t will reflect on a aswell
t,a

(tensor([1, 1, 2, 3]),
 tensor([[1, 1],
         [2, 3]]))

In [67]:
#stackingggggggg
a_stacked = torch.stack([a,b])
a_stacked

tensor([[[1, 1],
         [2, 3]],

        [[4, 5],
         [6, 7]]])

In [68]:
a_stacked = torch.stack([a,b], dim=1)
a_stacked

tensor([[[1, 1],
         [4, 5]],

        [[2, 3],
         [6, 7]]])

In [69]:
a,b

(tensor([[1, 1],
         [2, 3]]),
 tensor([[4, 5],
         [6, 7]]))

In [70]:
a_stacked = torch.stack([a,b], dim=2)
a_stacked

tensor([[[1, 4],
         [1, 5]],

        [[2, 6],
         [3, 7]]])

In [71]:
a_stacked[0], a[0], b[0]

(tensor([[1, 4],
         [1, 5]]),
 tensor([1, 1]),
 tensor([4, 5]))

### Squeezeeeeeee
removes all single dims from target tensor

In [85]:
a_reshaped = a.reshape(1,1,4)

In [86]:
a_reshaped, a_reshaped.shape

(tensor([[[1, 1, 2, 3]]]), torch.Size([1, 1, 4]))

In [89]:
a_squeezed = a_reshaped.squeeze()
a_squeezed

tensor([1, 1, 2, 3])

### Unsuqeeze
adds a single dimension to a target tensor at a specific dim

In [96]:
a_unsqueezed = a_squeezed.unsqueeze(dim = 0)
a_unsqueezed, a_unsqueezed.shape


(tensor([[1, 1, 2, 3]]), torch.Size([1, 4]))

In [97]:
a_unsqueezed  = a_squeezed.unsqueeze(dim = 1)
a_unsqueezed, a_unsqueezed.shape

(tensor([[1],
         [1],
         [2],
         [3]]),
 torch.Size([4, 1]))

### Permute
rearrangment of dims, returns view of tensor

In [ ]:
x_og = torch.rand(size=(224,224,3)) # color channel
x_og.shape

torch.Size([224, 224, 3])

In [113]:
x_permuted = x_og.permute(2,0,1) # rearrange by giving which dimenison to put where
x_permuted.shape                   # now it's rearranged to iykyk

torch.Size([3, 224, 224])

In [112]:
x_og[0,0,0] = 1

In [115]:
x_og[0,0,0], x_permuted[0,0,0] # seeee, it is a view of the original tensor

(tensor(1.), tensor(1.))