In [1]:
print("Yoo wasssup!")

Yoo wasssup!


In [2]:
!nvidia-smi

Sun Nov  9 03:08:11 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 555.99                 Driver Version: 555.99         CUDA Version: 12.5     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce GTX 1650      WDDM  |   00000000:01:00.0 Off |                  N/A |
| N/A   52C    P8              5W /   50W |     214MiB /   4096MiB |     18%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [3]:
import torch 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)
print(torch.cuda.is_available())

2.5.1+cu121
True


### Tensors

In [10]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [11]:
scalar.ndim

0

Get tensor value


In [13]:
scalar.item()

7

In [20]:
vector = torch.tensor([1,2,3])

In [21]:
vector

tensor([1, 2, 3])

In [22]:
vector.ndim

1

In [33]:
vector.shape
vector[1]

tensor(2)

In [24]:
matrix = torch.tensor([[1,2], [3,4]])
matrix

tensor([[1, 2],
        [3, 4]])

In [26]:
matrix.ndim

2

In [28]:
matrix.shape

torch.Size([2, 2])

In [31]:
matrix[1][0]

tensor(3)

In [43]:
tensor = torch.tensor([[[1,2,1],[3,4,2]],
                       [[4,5,3], [7,8,4]]])
tensor

tensor([[[1, 2, 1],
         [3, 4, 2]],

        [[4, 5, 3],
         [7, 8, 4]]])

In [44]:
tensor.shape

torch.Size([2, 2, 3])

In [45]:
tensor.ndim

3

### Random Tensors

They are very important, cause neural networks start with tensor full of rand num and adjust that number


In [51]:
rand_tensor = torch.rand(3,3,4)
rand_tensor

tensor([[[0.5771, 0.5754, 0.9809, 0.0059],
         [0.9364, 0.8841, 0.0922, 0.1580],
         [0.3688, 0.2021, 0.3280, 0.4537]],

        [[0.3107, 0.7784, 0.7562, 0.7940],
         [0.6320, 0.5776, 0.4415, 0.3641],
         [0.4531, 0.9076, 0.6593, 0.0992]],

        [[0.7672, 0.4232, 0.4759, 0.3714],
         [0.5175, 0.6975, 0.0806, 0.6303],
         [0.4573, 0.5251, 0.6639, 0.0930]]])

In [55]:
rand_tensor.ndim


3

In [58]:
rand_img = torch.rand(224,224,3) #images are used like this
rand_img.shape, rand_img.ndim

(torch.Size([224, 224, 3]), 3)

In [59]:
rand_tens = torch.rand(5,6)
rand_tens

tensor([[0.8932, 0.8225, 0.4637, 0.3943, 0.3110, 0.2386],
        [0.6685, 0.4470, 0.7546, 0.4277, 0.8265, 0.9649],
        [0.2705, 0.6416, 0.1110, 0.7547, 0.1271, 0.6156],
        [0.8335, 0.8355, 0.2461, 0.8081, 0.2733, 0.1476],
        [0.2240, 0.4610, 0.3574, 0.1297, 0.5022, 0.1634]])