In [1]:
import torch

In [2]:
rand_tensor = torch.rand(7,7)
rand_tensor

tensor([[0.2813, 0.8014, 0.5332, 0.0766, 0.2854, 0.5548, 0.0113],
        [0.8664, 0.4195, 0.6687, 0.9399, 0.9750, 0.1304, 0.7223],
        [0.6824, 0.1002, 0.1249, 0.3144, 0.8190, 0.6492, 0.0879],
        [0.8615, 0.4236, 0.3655, 0.5950, 0.1782, 0.3839, 0.0954],
        [0.2498, 0.1954, 0.9991, 0.9417, 0.5046, 0.6792, 0.3286],
        [0.8449, 0.1922, 0.7900, 0.3177, 0.6126, 0.8763, 0.2012],
        [0.3167, 0.2514, 0.3487, 0.7538, 0.9928, 0.4538, 0.8078]])

In [3]:
temp_tensor = torch.rand(1,7)
temp_tensor

tensor([[0.4675, 0.3075, 0.6161, 0.0662, 0.4838, 0.3229, 0.6702]])

In [4]:
mat_mul = torch.matmul(rand_tensor, temp_tensor.T)
mat_mul

tensor([[1.0363],
        [2.0062],
        [1.1124],
        [1.0718],
        [1.5383],
        [1.6761],
        [1.6583]])

In [5]:
torch.manual_seed(0)
rand_tensor = torch.rand(7,7)

temp_tensor = torch.rand(1,7)

mat_mul = torch.matmul(rand_tensor, temp_tensor.T)
mat_mul, temp_tensor, rand_tensor

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 tensor([[0.4820, 0.8198, 0.9971, 0.6984, 0.5675, 0.8352, 0.2056]]),
 tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
         [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
         [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
         [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
         [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
         [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
         [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]]))

In [6]:
torch.cuda.manual_seed(21)
rand1 = torch.rand(2,3, device="cuda")
rand2 = torch.rand(2,3, device="cuda")

In [7]:
rand1, rand2

(tensor([[0.4640, 0.6390, 0.6338],
         [0.8391, 0.1766, 0.3616]], device='cuda:0'),
 tensor([[0.5944, 0.7960, 0.9357],
         [0.5400, 0.7585, 0.7843]], device='cuda:0'))

In [8]:
gpu_matmul = torch.mm(rand1, rand2.T)
gpu_matmul

tensor([[1.3775, 1.2323],
        [0.9777, 0.8707]], device='cuda:0')

In [9]:
gpu_matmul.max()

tensor(1.3775, device='cuda:0')

In [10]:
gpu_matmul.argmax()
    

tensor(0, device='cuda:0')

In [11]:
gpu_matmul.argmin()

tensor(3, device='cuda:0')

In [12]:
humongous_chungus = torch.rand(1,1,1,10)
not_so_humongous_chungus = humongous_chungus.squeeze()

In [13]:
not_so_humongous_chungus.shape

torch.Size([10])