In [1]:
import torch

In [4]:
rand_tensor = torch.rand(7,7)
rand_tensor

tensor([[0.1500, 0.3437, 0.5692, 0.2634, 0.9722, 0.4028, 0.7962],
        [0.9080, 0.8748, 0.3007, 0.8335, 0.9675, 0.2459, 0.2143],
        [0.0232, 0.9873, 0.2150, 0.6170, 0.4947, 0.6434, 0.5226],
        [0.0587, 0.4529, 0.6822, 0.3213, 0.1204, 0.7581, 0.8469],
        [0.4272, 0.1513, 0.4889, 0.8414, 0.4973, 0.9509, 0.3968],
        [0.0408, 0.7093, 0.7938, 0.9094, 0.0691, 0.4054, 0.4609],
        [0.9471, 0.9467, 0.6932, 0.8612, 0.1365, 0.3345, 0.6091]])

In [6]:
temp_tensor = torch.rand(1,7)
temp_tensor

tensor([[0.5381, 0.7239, 0.1010, 0.2312, 0.8576, 0.8965, 0.2179]])

In [9]:
mat_mul = torch.matmul(rand_tensor, temp_tensor.T)
mat_mul

tensor([[1.8162],
        [2.4417],
        [2.0064],
        [1.4700],
        [1.9487],
        [1.3489],
        [2.0136]])

In [10]:
torch.manual_seed(0)
rand_tensor = torch.rand(7,7)

temp_tensor = torch.rand(1,7)

mat_mul = torch.matmul(rand_tensor, temp_tensor.T)
mat_mul, temp_tensor, rand_tensor

(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 tensor([[0.4820, 0.8198, 0.9971, 0.6984, 0.5675, 0.8352, 0.2056]]),
 tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
         [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
         [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
         [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
         [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
         [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
         [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]]))

In [19]:
torch.cuda.manual_seed(21)
rand1 = torch.rand(2,3, device="cuda")
rand2 = torch.rand(2,3, device="cuda")

In [20]:
rand1, rand2

(tensor([[0.4640, 0.6390, 0.6338],
         [0.8391, 0.1766, 0.3616]], device='cuda:0'),
 tensor([[0.5944, 0.7960, 0.9357],
         [0.5400, 0.7585, 0.7843]], device='cuda:0'))

In [22]:
gpu_matmul = torch.mm(rand1, rand2.T)
gpu_matmul

tensor([[1.3775, 1.2323],
        [0.9777, 0.8707]], device='cuda:0')

In [23]:
gpu_matmul.max()

tensor(1.3775, device='cuda:0')

In [26]:
gpu_matmul.argmax()
    

tensor(0, device='cuda:0')

In [28]:
gpu_matmul.argmin()

tensor(3, device='cuda:0')

In [36]:
humongous_chungus = torch.rand(1,1,1,10)
not_so_humongous_chungus = humongous_chungus.squeeze()

In [37]:
not_so_humongous_chungus.shape

torch.Size([10])