In [3]:
import torch
from torch import nn

In [6]:
class Model(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.linear = nn.Linear(num_features,1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):
        out  = self.linear(features)
        out  = self.sigmoid(out)

        return out
    

In [8]:
features = torch.rand(10,5)
model = Model(features.shape[1])

model(features)

tensor([[0.4052],
        [0.4045],
        [0.3913],
        [0.4102],
        [0.3899],
        [0.4134],
        [0.4213],
        [0.3863],
        [0.4189],
        [0.3691]], grad_fn=<SigmoidBackward0>)

In [11]:
model.linear.bias

Parameter containing:
tensor([-0.3915], requires_grad=True)

In [12]:
!pip install torchinfo

In [13]:
from torchinfo import summary

summary(model, features.shape)

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [21]:
class Model(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        # self.linear1 = nn.Linear(num_features,3)
        # self.relu = nn.ReLU()
        # self.linear2 = nn.Linear(3,1)
        # self.sigmoid = nn.Sigmoid()  This was aam zindagi

        self.network = nn.Sequential(   #Mentos zindagi type shiiii
            nn.Linear(num_features,3),
            nn.ReLU(),
            nn.Linear(3,1),
            nn.Sigmoid()
        )
       
    def forward(self, features):
        # out = self.linear1(features)
        # out = self.relu(out)
        # out = self.linear2(out)
        # out = self.sigmoid(out)  Boring stuffff

        out = self.network(features)

        return out
    

In [23]:
model = Model(features.shape[1])
model(features)

tensor([[0.3756],
        [0.3720],
        [0.3203],
        [0.3437],
        [0.3431],
        [0.3340],
        [0.3345],
        [0.3613],
        [0.3386],
        [0.3691]], grad_fn=<SigmoidBackward0>)

In [24]:
summary(model, features.shape)

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [27]:
model.linear1.weight

AttributeError: 'Model' object has no attribute 'linear1'