In [36]:
import torch
from torch import nn

In [37]:
class Model(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.linear = nn.Linear(num_features,1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):
        out  = self.linear(features)
        out  = self.sigmoid(out)

        return out
    

In [38]:
features = torch.rand(10,5)
model = Model(features.shape[1])

model(features)

tensor([[0.7062],
        [0.6504],
        [0.7294],
        [0.6769],
        [0.6935],
        [0.6447],
        [0.6739],
        [0.7651],
        [0.7750],
        [0.7662]], grad_fn=<SigmoidBackward0>)

In [39]:
model.linear.bias

Parameter containing:
tensor([0.1880], requires_grad=True)

In [40]:
!pip install torchinfo

In [41]:
from torchinfo import summary

summary(model, features.shape)

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [42]:
class Model(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        # self.linear1 = nn.Linear(num_features,3)
        # self.relu = nn.ReLU()
        # self.linear2 = nn.Linear(3,1)
        # self.sigmoid = nn.Sigmoid()  This was aam zindagi

        self.network = nn.Sequential(   #Mentos zindagi type shiiii
            nn.Linear(num_features,3),
            nn.ReLU(),
            nn.Linear(3,1),
            nn.Sigmoid()
        )
       
    def forward(self, features):
        # out = self.linear1(features)
        # out = self.relu(out)
        # out = self.linear2(out)
        # out = self.sigmoid(out)  Boring stuffff

        out = self.network(features)

        return out
    

In [43]:
model = Model(features.shape[1])
model(features)

tensor([[0.6617],
        [0.6367],
        [0.6399],
        [0.6666],
        [0.6687],
        [0.6584],
        [0.6374],
        [0.6508],
        [0.6401],
        [0.6455]], grad_fn=<SigmoidBackward0>)

In [44]:
summary(model, features.shape)

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [52]:
model.network[0].weight

Parameter containing:
tensor([[-0.4132, -0.0894, -0.3783, -0.1421, -0.1316],
        [ 0.1763, -0.2016,  0.2769, -0.2341,  0.1864],
        [-0.1774,  0.2244,  0.3600, -0.1020,  0.3691]], device='cuda:0',
       requires_grad=True)